# Generated by Django 3.2.8 on 2023-02-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyCar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='amount_payable',
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rent',
            name='final_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='start_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
