# Generated by Django 3.2.8 on 2023-02-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyCar', '0002_auto_20230212_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='amount_payable',
            field=models.FloatField(max_length=10),
        ),
    ]
